export const SEED_CH14 = `-- Chapter 14: Interpretation of Statutes, Deeds and Documents
insert into public.mcq_questions (book_id, chapter_no, chapter_title, question_no, question, options, correct_index, hint)
select b.id, 14, 'Interpretation of Statutes, Deeds and Documents', v.question_no, v.question, v.options, v.correct_index, v.hint
from public.books b
cross join lateral (values
(1, 'Rule of liberal construction should generally be applied in which type of case.', '["criminal case","civil case","labour and welfare case","property case"]'::jsonb, 2, 'rule of liberal construction should generally be applied to labour and welfare case as it Involves question of facts.'),
(2, 'Which out of the following is/are presumption for interpretation of statute?', '["A statute is not Intended to be consistent with principles of international law","the state is not affected by a statute unless It specifically mention","guilty mind is required for a criminal act","all of the above"]'::jsonb, 3, 'all of the above are presumed for interpreting a statute'),
(3, 'According to Maxwell, interpretation of statues, a statute has been defined as:', '["the authenticity of morals and conduct","a fundamental right","social responsibility","a will of the legislature"]'::jsonb, 3, 'according to Maxwell, a statute has been defined as Will of the legislature.'),
(4, 'Which rule is also called as ''literal Legis'':', '["rule of literal construction","rule of reasonable construction","rule of reasonable construction","rule of beneficial construction"]'::jsonb, 0, 'rule of literal construction is also called ''literal Legis'''),
(5, 'In the process of interpretation, non-statutory aids are illustrated by:', '["common law rules of Interpretation","case law relating to Interpretation of statute","both of the above","none of the above"]'::jsonb, 2, 'in the process of interpretation, non- statutory aids are illustrated by common law rules of Interpretation and/or case law relating to interpretation of statute.'),
(6, 'The interpretation of statute''s primary rule of literal construction that suggests that interpretation should not be given such that they would make other provisions redundant was discussed in the case law.', '["Nand Prakash Vohra v State of HP Heydon''s case","Heydon''s case","K S Venkataraman & Co vs. State Of Madras","AK Gopalan vs. The State Of Madras Union"]'::jsonb, 0, 'Nand Prakash Vohra v state of HP, it was stated that interpretation should not be given such that they would make other provisions redundant.'),
(7, 'In the process of interpretation, statutory aids are illustrated by:', '["general clauses act","Specific definition contained In individual act","both of the above","none of the above"]'::jsonb, 2, 'in the process of Interpretation'' non statutory aids are illustrated by general clauses act and/or case law relating to Interpretation of statute.'),
(11, 'Where the words are used in different context, the word ''plant'' shall be given a different meaning when constructing the word ''plant and machinery'' and different when constructing the word ''plant and trees'' is example for which of the rule of interpretation:', '["rule of exceptional construction","noscitur a sociis","expression unis est exclusion alterius","contemporanea exposition"]'::jsonb, 1, 'rule of interpretation, noscitur a sociis means , the meaning of the words is derived from its associates words.'),
(12, 'The function of what is to except and to deal with a case, which would otherwise fall within the general enactment', '["title","proviso","schedule","margins"]'::jsonb, 1, 'proviso act as an exception, it deal with a case, which would otherwise fall within the general enactment.'),
(13, 'Which of the following statute is passed to cure defects in prior law and to validate legal proceedings, Instruments or acts of public and private administrative powers?', '["Declaratory","curative","consolidating","restraining"]'::jsonb, 1, 'curative statute is passed to cure defects in the prior law and to validate legal proceedings, instruments or acts of public and private administrative powers.'),
(14, 'Which rule of Interpretation means, interpreting a statute or other document by reference to the exposition it has received from contemporary authority', '["rule of exceptional construction","noscitur a sociis","expression unis est exclusion alterius","contemporanea exposition"]'::jsonb, 3, 'the maxim Contemporanea exposition means interpreting a statue or other document by reference to the exposition it has received from contemporary authority.'),
(16, 'Which statute either expressly or by necessary Implication revokes or terminates another statute', '["repealing statute","declaratory statute","amending statute","codifying statute"]'::jsonb, 0, 'repealing statute either expressly or by necessary implication revoke or terminates another statute).'),
(17, 'Which of the following word generally act as a Disjunctive word while interpretation', '["or","and","shall","may"]'::jsonb, 0, 'the word ‘or’ generally act as a Disjunctive word while interpretation'),
(18, 'For imposing social conduct on people, certain laws are enacted by the legislature for imposing fines and penalty on wrong doer, the law is called:', '["criminal law","property law","law of tort","penal laws"]'::jsonb, 3, 'penal laws are enacted by the legislature for imposing fines and penalty on wrong doer.'),
(19, 'Which of the following word is construed as compulsory, whenever the object of the power is to give effect to a legal right and has discretion coupled with an obligation', '["may","must","shall","should"]'::jsonb, 0, 'The word ''may is construed as compulsory, whenever the object of the power is to give effect to a legal right and has discretion coupled with an obligation.'),
(20, 'The general words must follow the specific words is condition of which rule of interpretation:', '["rule of literal construction","rule of reasonable construction","rule of harmonious construction","rule of ejusdem generis"]'::jsonb, 3, 'The general words must follow the specific words is condition of rule of ejusdem generis.'),
(23, 'What is not interpreted as stating a general rule:', '["Explanations","Interpretation Clause","marginal notes","proviso"]'::jsonb, 1, 'Proviso are is not interpreted as stating a general rule.'),
(24, 'The term ''Ejusdem Generis'' means:', '["at the generic nature","general interpretation","general law of statute","of the same class/species"]'::jsonb, 3, 'The primary rule of interpretatio n called Ejusdem Genes means of the same class/specie'),
(26, 'Rule of strict construction should generally be applied in which type of case:', '["criminal case","civil case","labour and welfare case","marriage case"]'::jsonb, 0, 'Strict construction must be applied to Criminal statutes This means that a criminal statute may not be enlarged by implication or intent beyond the fair meaning of the language used or the meaning that is reasonably justified by its terms.'),
(27, 'In which case supreme court observed that principles of interpretation can be applied only if there is an ambiguity in a provision, and not permissible first to create an artificial ambiguity.', '["CIT vi Indian Bank ltd. AIR (1965) SC 1473","Saleh Bros. V K Rajendran and Anr., AIR 1970 Mad 165,","Nagpur Railway Co. Ltd, v. Ruttanp Ramp, AIR 1938 PC 67.","Mercara v. KodimaniandraDeviah, AIR 1962 SC 847."]'::jsonb, 0, 'in case CIT v. Indian Bank ltd. AIR (1965) SC 1473'),
(28, 'Consolidating statutes and previous law is aid of interpretation.', '["internal","external","all of the above","none of the above"]'::jsonb, 1, 'consolidating statutes and previous law is external aid of interpretation'),
(29, 'Which of the following are not internal or intrinsic aids to interpretation:', '["schedule","proviso","punctuation","none of the above"]'::jsonb, 3, 'All of them are Internal or Intrinsic aids to Interpretation.'),
(30, 'Which of the following word when used would not of itself make the provision of the act mandatory, but prima facie when used by statute. it is mandatory', '["may","must","shall","should"]'::jsonb, 2, 'The word ‘shall’ when used not of itself make the provision of the act mandatory, but prime facie when used by statute, it is mandatory.'),
(35, 'Authentic Interpretation falls under which branch of interpretation:', '["legal interpretation","usual interpretation","Doctrinal interpretation","logical Interpretation"]'::jsonb, 0, 'Authentic interpretation falls under legal interpretation'),
(36, 'When there are two or more provisions which cannot be reconciled with each other they should be interpreted, whenever possible as to give effect to all of them is given in which of the following rule of construction', '["rule of literal construction","rule of reasonable construction","rule of harmonious construction","rule of beneficial construction"]'::jsonb, 2, NULL),
(37, 'Which out of the following aid does the court use for interpreting the statute:', '["parliamentary history","foreign decisions","dictionaries","all of the above"]'::jsonb, 3, 'Any aid that Is legal can be used by court.'),
(38, 'Which among the following Is false: Statute are commonly divided into:', '["general","codifying","remedial","disabling"]'::jsonb, 0, 'General statute is not a category of statute'),
(39, 'In which of the following rule of construction the words of statute must be constructed so as to lead to a sensible meaning', '["rule of literal construction","rule of reasonable construction","rule of harmonious construction","rule of beneficial construction"]'::jsonb, 1, 'Under rule or reasonable construction the words at statute must be Constructed so as to lead to a sensible meaning'),
(40, 'Rule of beneficial construction is also called:', '["ut res magis valeat quam pereat rule","heydon rule","aquo tacit per allum per se rule","all of the above."]'::jsonb, 1, 'Rule of beneficial construction is also called heydon rule'),
(41, 'What is the process by which the real meaning of the act or a document and the intention of the legislature in enacting it is ascertained?', '["preamble","statutes","interpretation","construction"]'::jsonb, 2, 'Interpretation is the process by which the real meaning of the act or a document and the intention of the legislature in enacting it is ascertained.'),
(42, 'Which of the following interpretation applies when there is actual rule of law which binds the judge to place a certain interpretation of the statute:', '["Doctrinal interpretation","legal interpretation","usual Interpretation","logical interpretation"]'::jsonb, 1, 'legal interpretation applies when there is actual rule of law which binds the Judge to place a certain interpretation of the statute.'),
(43, 'What is termed as drawing of conclusion respecting subjects that lie beyond the direct expression of the text:', '["interpretation","construction","summary","plaint"]'::jsonb, 1, 'construction is termed as drawing of conclusion respecting subjects that lie beyond the direct expression of the text.'),
(44, 'In which case it was decided that it is the duty of the court to give effect to the meaning of the act when the meaning can be known', '["State of Bihar v. CIT","CWT v. Smt. Muthu Zulaika","State of Madras v. Gannon Dunkerly C. AIR 1958","Bhagwati Prasad Kedia v. CIT(2001)"]'::jsonb, 2, 'It is the duty of the court to give effect to the meaning of an act when the meaning can be equitably gathered from the words used (State of Madras v. Gannon Dunkerly C. AIR1958)'),
(45, 'Grammatical interpretation falls under which branch of interpretation:', '["legal interpretation","usual interpretation","Doctrinal interpretation","logical interpretation"]'::jsonb, 2, 'grammatical interpretation falls under Doctrinal interpretation.'),
(46, 'All instruments are deeds. The statement is', '["correct","incorrect","partly correct","partly incorrect"]'::jsonb, 1, 'deeds are instruments. but all instruments are not deed'),
(47, 'Which term means a paper or any other material thing giving information, proof or evidence of anything?', '["Document","Instrument","agreement","Deed"]'::jsonb, 0, 'a Document means a paper or any other material thing giving information, proof or evidence of anything.'),
(48, 'An internal aid that may be added to include something within the section or to exclude something from it, Is—', '["Proviso","Explanation","Schedule","Illustrations"]'::jsonb, 1, NULL),
(49, 'Which is the element of document by which a mental or intellectual elements comes to find a permanent form.', '["matter","record","substance","means"]'::jsonb, 2, 'substance is the third element of document by which a mental or Intellectual elements comes to find a permanent form'),
(50, 'According to the mischief rule , the court while applying the rule should consider:', '["what was the common law before making the act","what remedy the parliament has resolved and appointed to cure and true reason of the remedy","what was the mischief and defect for which the common law did not provide","all of the above"]'::jsonb, 3, 'the court while applying the mischief rule should consider all the above parameters.'),
(51, 'Which out of the following is not an external aid in interpretation?', '["explanations","reference to other statute","reference to reports","dictionaries"]'::jsonb, 0, 'explanations cannot be said as aid in interpretation.'),
(54, 'According to harmonious construction, it is the duty of whom to avoid a clash between two section of the same act:', '["plaintiff","defendant","court","government"]'::jsonb, 2, 'according to harmonious construction, it is the duty of the court to avoid a clash between two section of the same act'),
(55, 'Which of the following interpretation applies to ordinary rules or speech to find out meanings of the Words:', '["authentic interpretation","usual interpretation","grammatical interpretation","logical interpretation"]'::jsonb, 2, 'grammatical interpretation applies to ordinary rules of speech to find out meanings of the words.'),
(56, 'In which of the following rule of construction if a word has a definite and clear meaning, it should be Interpreted with that meaning only, Irrespective of its consequences.', '["rule of literal construction","rule of reasonable construction","rule of harmonious construction","rule of beneficial construction"]'::jsonb, 0, 'under rule of literal construction. If a word has a definite and clear meaning, it should be interpreted with that meaning only. Irrespective of Its consequence.')
) as v(question_no, question, options, correct_index, hint)
where b.title = 'CA Inter Law MCQs by Darshan Khare'
on conflict (book_id, chapter_no, question_no) do nothing;
`;
