export const SEED_CH5 = `-- Chapter 5: Acceptance of Deposit by Companies
insert into public.mcq_questions (book_id, chapter_no, chapter_title, question_no, question, options, correct_index, hint)
select b.id, 5, 'Acceptance of Deposit by Companies', v.question_no, v.question, v.options, v.correct_index, v.hint
from public.books b
cross join lateral (values
(1, 'M/s ABC Ltd is a Public Limited company having net worth of Rs. 120 Cr. and turnover of Rs. 100 Cr. Whether the company is eligible to accept deposit from Public?', '["Yes","No","Partly Yes","Partly No"]'::jsonb, 0, 'As per Section 76(1) of the Companies Act, 2013, a Public Company having Net worth ≥ Rs. 100 Cr. Or Turnover ≥ Rs. 500 Cr. are eligible to accept deposits from Public.'),
(2, 'M/s XYZ Ltd is a Public Limited company having net worth of Rs. 80 Cr. and turnover of Rs. 600 Cr. Whether the company is eligible to accept deposit from Public?', '["Yes","No","Partly Yes","Partly No"]'::jsonb, 0, 'As per Section 76(1) of the Companies Act, 2013, a Public Company having Net worth ≥ Rs. 100 Cr. Or Turnover ≥ Rs. 500 Cr . are eligible to accept deposits from Public.'),
(3, 'A company shall issue circular to its members inviting deposits. The circular shall include a statement containing………', '["Financial position of the company","The credit rating obtained by the company","Total numbers of depositors & amount due towards deposits in respect of old deposits","All of the above and such other particulars in such form and manner as may be prescribed."]'::jsonb, 3, 'Section 73(2) of the Companies Act, 2013.'),
(4, 'Any concerned depositor can make an application to the…………. If a company fails to repay the deposits or part thereof or any interest thereon.', '["Board of Directors","RBI","High Court","NCLT"]'::jsonb, 3, 'Section 73(4) of the Companies Act, 2013.'),
(5, 'A small depositor means a depositor who has deposited in a financial year a sum not exceeding…….', '["Ten Thousand rupees","Fifteen Thousand rupees","Twenty Thousand rupees","Fifty Thousand rupees"]'::jsonb, 2, NULL),
(6, 'Company shall file circular and statement regarding public deposits with ROC within ………days.', '["10 days","20 days","30 days","45 days"]'::jsonb, 2, 'Section 73(2) of the Companies Act, 2013.'),
(7, 'A sum not less than 15% of deposits maturing in current year + in next financial year shall be deposited in …………………. Account at a scheduled bank.', '["Free Reserve","Securities Premium Account","Capital redemption reserve Account","Deposit Repayment Reserve Account"]'::jsonb, 3, 'Section 73(2) of the Companies Act, 2013.'),
(8, 'The Deposit Repayment Reserve Account shall be used exclusively for the purpose of …………. Only.', '["Redemption of preference shares","Payment of dividend","Issue of Bonus shares","Repayment of deposits only"]'::jsonb, 3, 'Section 73(5) of the Companies Act, 2013.'),
(9, 'Acceptance of deposits from public required …………. Resolution of general meeting of members.', '["General Resolution","Special Resolution","unanimous Resolution","not required any resolution of members"]'::jsonb, 1, 'Section 76(1) of the Companies Act, 2013.'),
(10, 'A Public Company having net worth …………. Or turnover………….are eligible to accept deposits from Public.', '["Net worth ≥ Rs. 100 Cr. or Turnover ≥ Rs. 500 Cr.","Net worth ≥ Rs. 50 Cr. or Turnover ≥ Rs. 500 Cr.","Net worth ≥ Rs. 100 Cr. or Turnover ≥ Rs. 1000 Cr.","Net worth ≥ Rs. 50 Cr. or Turnover ≥ Rs. 1000 Cr."]'::jsonb, 0, 'Section 76(1) of the Companies Act, 2013.'),
(11, 'If the eligible company is accepting deposits u/s 180(1) (c) then prior consent using ……. Resolution of General Meeting.', '["General Resolution","Special Resolution","unanimous Resolution","not required any resolution of members"]'::jsonb, 0, 'Section 76(1) of the Companies Act, 2013.'),
(12, 'M/s XYZ Ltd is a Public Limited company having net worth of Rs. 80 Cr. and turnover of Rs. 400 Cr. Whether the company is eligible to accept deposit from members?', '["Yes","No","Partly Yes","Partly No"]'::jsonb, 0, 'As per Section 73 of the Compan ies Act, 2013, every Public Company are eligible to accept deposits from members after passing special resolution in General meeting.'),
(13, 'Any person who deposits the amount but not get re-paid in specific due time either principal or interest then he can apply to……….', '["Board of Directors","RBI","High Court","NCLT"]'::jsonb, 3, 'As per Section 73 and 76 of the Companies Act, 2013.'),
(14, 'Return of deposit to be filed with Registrar of Companies in Form No………….', '["Form DPT 1","Form DPT 2","Form DPT 3","Form DPT 4"]'::jsonb, 2, 'As per Section 73 of the Companies Act, 2013.'),
(15, 'Appointment of trustee for depositors in Form No………….', '["Form DPT 1","Form DPT 2","Form DPT 3","Form DPT 4"]'::jsonb, 1, 'As per Section 76(1) of the Companies Act, 2013.'),
(16, 'The company accepting secured deposits shall, within …….. Days of such acceptance, create a charge on its assets.', '["10 days","20 days","30 days","45 days"]'::jsonb, 2, 'As per Section 76(1) of the Companies Act, 2013.'),
(17, '………..is required for accepting deposits from members.', '["Ordinary Resolution at General Meeting","Special Resolution at GM","Board Resolution","Both b and c"]'::jsonb, 0, 'A company may, subject to the passing of a resolution in general meeting and subject to such rules as may be prescribed in consu ltation with the Reserve Bank of India, accept deposits from its members.'),
(18, 'No company shall accept or renew any deposit from its members, if the amount of such deposits together with the amount of other deposits outstanding as on the date of acceptance or renewal of such deposits exceeds………….per cent of the aggregate of the…………. of the company.', '["15, paid up share capital and free reserves","15, paid up share capital, free reserves and Security Premium Account","35, paid up share capital, free reserves and Security Premium Account","35, paid up share capital and free reserves"]'::jsonb, 2, 'No company referred to in sub - section (2) of section 73 shall accept or renew any deposit from its members, if the amount of such deposits together with the amount of other deposits outstanding as on the date of acceptance or renewal of such deposits exceeds thirty five per cent of the aggregate of the Paid - up share capital, free Reserves and securities premium account of the company.'),
(19, 'No eligible company shall accept or renew deposit from non-members, if the amount of such deposit together with the amount of such other deposits, other than member deposits, outstanding on the date of acceptance or renewal exceeds……….% of aggregate of the Paid-up share capital, free Reserves and securities premium account of the company.', '["10","15","25","35"]'::jsonb, 2, 'No eligible company shall accept or renew deposit from non - members, if the amount of such deposit together with the amount of such other deposits, other than member deposits, outstanding on the date of acceptance or renewal exceeds 25% of aggregate of the Paid - up share capital, fre e Reserves and securities premium account of the company.'),
(20, 'Deposits may be accepted in joint names not exceeding……….', '["2","3","5","10"]'::jsonb, 1, 'Where depositors so desire, deposits may be accepted in joint names not exceeding three, with or without any of the clauses, namely, "Jointly", "Either or Survivor, "First named or Survivo r", "Anyone or Survivor".'),
(21, 'No Government shall accept or renew any deposit, if the amount of such deposits together with the amount of other deposits outstanding as on the date of acceptance or renewal exceeds ………..% of the aggregate of its Paid-up share capital, free Reserves and securities premium account of the company.', '["10","15","25","35"]'::jsonb, 3, 'No Government company eligible to accept deposits shall accept or renew any deposit. If the amount of such deposits together with the amount of other deposits outstanding as on the date of acceptance or renewal exceeds thirty five per cent. Of the aggregate of its Paid - up share capital, free Reserves and securities premium account of the company.'),
(24, 'Every company shall pay a penal rate of interest of ………. p.a. for the overdue period in case of deposits, whether secured or unsecured, matured and claimed but remaining unpaid.', '["12","18","24","30"]'::jsonb, 1, 'Every company shall pa y a penal rate of Interest of 18% p.a. for the overdue period in case of deposits, whether secured or unsecured, matured and claimed but remaining unpaid.'),
(25, 'Every company accepting deposits shall on or before……………. of every year, file with the Registrar, a return in Form DPT-3', '["31 st May","30 th June","31 st July","31 st August"]'::jsonb, 1, 'Every company accepting deposits shall on or'),
(26, 'Section 73 prohibits a company to invite, accept or renew deposits from public. This prohibition Is applicable to :-', '["Banking company","Non- banking financial company","One person company","Company as may be specified by Central Government."]'::jsonb, 2, 'Restriction on acceptance of deposits from public shall not'),
(27, 'No eligible company shall accept or renew any deposit from its members, if the amount of such deposit together with the amount of deposits outstanding as on the date of acceptance or renewal of such deposits from members exceeds ……….% of the aggregate of the Paid-up share capital, free Reserves and securities premium account of the company.', '["10%","15%","25%","35%"]'::jsonb, 0, 'No eligible company shall accept or renew a ny deposit'),
(28, 'A company accepting deposits shall deposit such sum which shall not be less than ……….. % of the amount of its deposits maturing during a financial year and the financial year next following, and keep it in a scheduled bank in a separate bank account.', '["10","15","20","25"]'::jsonb, 1, 'A company accepting deposits'),
(29, 'Acceptance of deposits from members required …………. Resolution of general meeting of members.', '["General Resolution","Special Resolution","unanimous Resolution","not required any resolution of members"]'::jsonb, 1, 'Section 73(2) of the Companies Act, 2013.'),
(30, 'A sum not less than ……….of deposits maturing in current year + in next financial year shall be deposited in ‘Deposit Repayment Reserve Account’ at a scheduled bank.', '["7%","10%","15%","20%"]'::jsonb, 2, 'Section 73(2) of the Companies Act, 2013.')
) as v(question_no, question, options, correct_index, hint)
where b.title = 'CA Inter Law MCQs by Darshan Khare'
on conflict (book_id, chapter_no, question_no) do nothing;
`;
