export const SEED_CH11 = `-- Chapter 11: Indian Contract Act, 1872
insert into public.mcq_questions (book_id, chapter_no, chapter_title, question_no, question, options, correct_index, hint)
select b.id, 11, 'Indian Contract Act, 1872', v.question_no, v.question, v.options, v.correct_index, v.hint
from public.books b
cross join lateral (values
(1, 'In the case of rights to sell the goods of Pawnee, if the Pawnor fails to pay the money due under the pledge, and the Pawnee sells the good. If proceeds of sale is greater than amount due, what will be the effect of such sale?', '["The Pawnee will retain the money","The Pawnee will retain the half of the money","The Pawnee shall pay the surplus to the Pawnor","None of the above"]'::jsonb, 2, 'According to Section 176, if the Pawnor has failed to pay the debt or perform his promise, and the Pawnee has given a reasonable notice to the Pawnor of his intention to sell the goods. Then, if the proceeds of sale < Amount due: The Pawnee may recover the deficit from Pawnor, if the Proceeds of sale > Amount Due: The Pawnee shall pay the surplus to the Pawnor.'),
(2, 'A gives authority to B to sell A''s land, and to pay himself, out of the proceeds, the debts due to him from A. Decide whether A can revoke the authority of B?', '["A cannot revoke","A can revoke","A can revoke to some extent","Can''t Say"]'::jsonb, 0, 'According to section 202, it is the case of agency coupled with interest and hereunder, A cannot revoke the authority of B. Also, the agency cannot be terminated even in case of insanity or death of A.'),
(3, 'K is the wife of A. She purchased a saree on credit from B. B demanded the amount from A. A refused to make the payment. B filed a suit against A for the same amount. Decide in the light of provisions of the Indian Contract Act, 1872, whether B would succeed or not?', '["B is entitled to sue A","B Is entitled to sue K","B is not entitled to sue A & K","Can''t Say"]'::jsonb, 0, 'B is entitled to sue A, since a husband is liable for the necessities supplied to his wife and the wife has an implied authority to pledge his husband''s credit for necessities and hence it is a legal presumption that a married woman is an agent of her husband.'),
(4, 'What is the meaning of ''agent'' as per section 182?', '["A person employed to do any act for another","A person employed to represent another in dealing with third person","Either a or b","None of the above"]'::jsonb, 2, 'Accor ding to Section 182 under the contract of agency, an agent Is a person employed to do any act for another; or represent another in dealings with third person.'),
(5, 'When the Pawnee can retain the pledged goods?', '["When the promise is not performed","Interest on debt not paid","Necessary expenses for preservation of Goods","All of the above"]'::jsonb, 3, 'According to section 173, rights of Lien to Pawnee until the Pawnor has money due unde r the pledge (or until the promise Is performed), Interest on debt not paid, and necessary expenses for preservation of goods.'),
(6, 'R of New Delhi sends his agent M to purchase certain goods from Global Enterprise, Mumbai on credit for him. Later on R pays the amount for the goods purchased. On another occasion the agent sends M to purchase goods but this time pays sufficient cash to M for the purpose. M, however again purchases the goods from Global Enterprise but on credit and soon thereafter he dies. Global Enterprise files a suit against R for recovery of the said amount. Decide whether Global Enterprise would be given any relief by the court under the provisions of the Indian Contract Act, 1872?', '["R is not liable to Global Enterprise","M’s legal heir is liable to Global Enterprise","R is liable to Global Enterprise","None of the above"]'::jsonb, 2, 'R will be liable to Global Enterprise for goods purchased by M, since the principal is bound to third parties for all s uch acts of the agent as are within the scope of authority of the agent as a previous occasion, purchase of goods by M on behalf of R. and subsequent payment for such goods by R, established that it was within the scope of authority of M to purchase goods on credit on behalf of R.'),
(7, 'A hires a carriage of B and agrees to pay Rs. 500 as hire charges. The carriage is unsafe, though B is unaware of it A is injured and claims compensation for the injuries suffered by him. B refuses to pay. Discuss the liability of B?', '["B is not liable to pay the compensation","B is liable to pay the compensation","B is liable to pay half of the compensation of the damage so caused","B Is not liable to pay the compensation up to some extent"]'::jsonb, 1, 'Since the hire of carriage of B by an amounts to non - gratuitous benefit and It''s the duty of B to disclose to A that the carriage was unsafe (even though he was unaware about It), and hence B didn’t disclose the same to A. Thus, B is liable to compensate for the injuries suffered by B due to non - disclosure of faults In the carriage.'),
(8, 'During which circumstances Bailee shall not be liable for any loss or destruction of goods?', '["He Is not negligent","The loss was caused due to an act of god or other unavoidable reasons","Both a or b","None of the above"]'::jsonb, 2, 'According to Section 152 of the Indian Contract Act 1872, the Bailee shall not be liable for any loss or destruction of goods, if he is not negligent, or the loss was caused due to an act of God or other unavoidable reasons.'),
(9, 'P appoints Q, a minor to sell his car for not less than Rs. 2.5Iacs. Q sells it for Rs. 2Iacs, whether P will be bound by the transaction or the transaction will be revoked?', '["P will be bound to sell the car for Rs. 2lacs","P will be liable to compensate the party involved, in case of revocation","P will not be bounded by the transaction","None of the above"]'::jsonb, 0, 'P will be bound to sell the car for Rs. 2lacs and Q, the minor will not be liable to P, as according to Section 184, an agent is not liable to the principal if he is a minor or is of unsound mind.'),
(10, 'The Delivery of goods by one person to another as security for the payment of a debt is called ……….?', '["Bailment","Pledge","Mortgage","Hypothecation"]'::jsonb, 1, 'According to Section 172, the bailment of goods as a security for payment of a debt or performance of a promise is called pledge.'),
(11, 'A delivers a rough diamond to B, a jeweler, to be cut and polished, which is accordingly done. Does B has particular lien for his liability if not been paid by A with context on contract of Bailment?', '["B Is entitled to retain the Diamond","B is not entitled to retain the Diamond","A can regain its possession back, only any part payment made thereon","Can''t say"]'::jsonb, 0, 'According to Section 170 of the Indian Contract Act, 187 2, B is entitled to retain the diamond till he is paid for the service he has rendered (B has particular Lien).'),
(12, 'Do the seizure of goods by custom authorities constitute a contract of bailment under the provisions of the Indian Contract Act, 1872?', '["No","Yes","Partly yes and Partly no","Can’t say"]'::jsonb, 1, 'Yes, it result in a valid contract of bailment, as all the essentials of a valid contract of bailment are satisfied in such a case.'),
(15, 'What are the duties of an agent amongst the following?', '["To conduct the business In accordance with the directions given by the principal","Not to make any secret profit out of the agency business other than the agreed remuneration","No to use Information obtained In the course of the agency against principal","All of the above"]'::jsonb, 3, 'According to Section - 209 to 218, as per the contract of agency under the Indian Contract Act, 1872, there are various other duties along with the above duties are given thereon.'),
(16, 'What are the rights of an agent amongst the following?', '["To retain money out of the sums received In agency business for advances made or expenses Incurred and remuneration due to him","To claim compensation for injury caused to agent because of principal''s neglect or want of skill","Right of Lien on principal''s goods, papers and other property until the remuneration due to him is paid","All of the above"]'::jsonb, 3, 'Refer to section 217 and 220 to 225, for the various other Rights of an agent, as per given in the Indian Contract Act, 1872.'),
(20, 'Which among the following can become an agent?', '["A minor","A person of unsound mind","Neither a nor b","Both a or b"]'::jsonb, 3, 'According to Section 184 under the contract of agency, any person may become an agent, even a minor or a person of unsound minor can become an agent.'),
(21, 'Mercantile Agent means an agent having the authority to……………………..?', '["Perform a particular act","Do all acts connected with a particular business of the principal","Act under the control of the original agent","Consign the goods for the purpose of sale"]'::jsonb, 3, 'Mercantile agent means an agent having the authority to sell the goods, consign the goods for the purchase of sale, buy the goods, raise money on the security of the goods, acting as agent in the ordinary course of business.'),
(22, 'Mr. A of Alwar engaged Mr. S as his agent to buy a house. Mr. S bought a house for Rs. 40 Lakhs in the name of a nominee and then purchased it himself for Rs. 44 Lakhs. He then sold the same house to Mr. A for Rs. 46 Lakhs. Mr. A later comes to know about the mischief of Mr. S and tries to recover the excess amount paid to Mr. S. Is he entitled to recover any amount from Mr. S and by how much?', '["Mr. A is not entitled to recover any amount from Mr. S","Mr. A Is entitled to repudiate the contract or to claim from Mr. S Rs. 6 lakhs","Mr. A is entitled to recover Rs. 4 lakhs from Mr. S","Mr. A Is entitled to repudiate the contract or to claim from Mr. S Rs. 2 Lakhs"]'::jsonb, 1, 'Non - disclosure of profit of Rs. 6 Lakhs amounts to br each of duty by Mr. S, since Mr. S without disclosing all the material facts and without obtaining the consent of Mr. A, dealt in the business of agency on his own account and Mr. S made a secret profit, so Mr. A is entitled to repudiate the contract or to claim from Mr. S Rs. 6 Lakhs.'),
(23, 'An agency in which the agent himself has interest in the subject matter of agency is called……………….?', '["Agency by estoppel","Agency by Holding Out","Agency by necessity","Agency coupled with interest"]'::jsonb, 3, 'As per Section 202, when an agency is created for securing some benefit to the agent over and above his remuneration as an agent, it is called as agency coupled with Interest.'),
(24, 'When an agent is considered as Agency by Estoppel?', '["Law treating one person as an agent of another","A person who makes a representation to a third person that a certain person is his agent","A person by his affirmative conduct lead third person to believe that doing some act on his behalf Is doing with authority.","None of the above"]'::jsonb, 1, 'According to Section 237 of t he contract of agency under the Indian Contract Act, 1872, an agency by estoppel is considered, if a person makes a representation to a third person that a certain person is his agent, and the third party, believing such representation to be true, enters i nto a contract with the pretended agent.'),
(25, 'Which among the following is to be considered as a Gratuitous Bailment?', '["For the exclusive benefit of Bailor","For the exclusive benefit of Bailee","For the mutual benefit of Bailor & Bailee","Both a or b"]'::jsonb, 3, 'Gratuitous Bailment is defined as the bailment without any charges or reward, i.e., no hire charges are be paid by Bailee and no custody charges are paid by Bailor.'),
(26, 'Define the term ''PAWNEE'' under the contract of Pledge?', '["The Bailor in case of a pledge","The Bailee in case of a pledge","The third party in case of a pledge","Related Party of a Bailor"]'::jsonb, 1, 'According to Section 172, the Bailor in case of pledge is called as Pawnor and the Bailee in case of pledge is called as Pawnee.'),
(27, 'When the goods are mixed without Bailor''s consent and goods are not separable, then what will be the consequences of the same?', '["The parties will have a proportionate interest in such mixture","The Bailee shall pay the expenses of damage of separation","The Bailee is not liable for it","The Bailee shall be liable to pay damages to the Bailor for any loss caused to him"]'::jsonb, 3, 'According to Section 157 of the Indian Contract Act, 1872, the Bailee shall be liable to pay damages to the Bailor for any loss caused to him as t he goods are mixed without Bailor''s consent and goods are not separable.'),
(28, 'When the Bailee has the right to be indemnified by the Bailor?', '["When the Bailor has no title to the goods.","When the Bailee suffers any loss, caused because of Bailor","Both a and b","None of the above"]'::jsonb, 2, 'According to Section 166, the Bailee has the right to be Indemnified by the Bailor, If the Bailor has no title to the goods, and as a consequence, the Bailee suffers from lo ss.'),
(29, 'A (n)…………. is a contract a principal and agent enter into that says the principal cannot employ another agent other than the one stated.', '["Ratified Contract","Exclusive Agency Contract","Apparent agency contract","Exclusive principle contract"]'::jsonb, 1, 'If principal and an agent enter into an exclusive agency contract, the principal cannot employ any agent other than the exclusive agent.'),
(32, 'Z guarantees to Y, to the extent of Rs. 2,000, payment for rice to be supplied by Y to X. Y supplies to X rice amounting to Rs. 500, but obtains from Z payment of the sum of Rs. 2000 in respect of the rice supplied. Decide whether Y can recover the amount from Z?', '["Y can recover from Z amounting Rs. 2,000","Y cannot recover from Z, more than Rs. 500","Y can recover from Z Rs. 500 and balance amount from X","Y can recover from Z Rs. 1500 and balance amount from X"]'::jsonb, 1, 'Y cannot recover fro m Z more than Rs. 500 as the market value of the amount actually supplied is tenable and cannot earn excess profit from it, without the consent of Z.'),
(33, 'S and P go into a shop. S says to the shopkeeper, C, "Let P have the goods, and if he does not pay you, I will. This is a ………', '["Contract of Guarantee","Contract of Indemnity","Wagering agreement","Quasi-contract"]'::jsonb, 0, NULL),
(34, 'What are the reason for loss that is to be considered under the contract of indemnity u/s 24?', '["Conduct of the promisor himself","Conduct of any other person","Any act event or accident which is not in the control of the parties Le. Act of God","Either a or b"]'::jsonb, 3, 'The Contract of Indemnity specifies that the Indemnity holder'),
(35, 'Bailment is an act of delivering…………?', '["Goods","Services","Goods and Services","None of the above."]'::jsonb, 0, 'According to Section 148 of the Indian Contract Act, 1872, a " Bailment'''),
(36, 'What is the form of contract under the contract of guarantee?', '["Must be oral","Must be written","Either oral or written","None of the above"]'::jsonb, 2, 'A contract'),
(37, 'Bhavan owes Chetan a debt guaranteed by Amit. Chetan does not sue Bhavan for a year after the debt has become payable. In the meantime, Bhuvan becomes insolvent. Is Amit discharged? Decide with reference to the provision of the Indian Contract Act, 1872?', '["Amit is discharged from his liability","Amit is discharged for half of the amount of Bhaven''s liability","Amit Is not discharged","None of the above"]'::jsonb, 2, 'Amit is not discharged, since mere preference on the part of the creditor to sue the principal debtor does not discharge the surety.'),
(38, 'What are the rights of indemnity holder u/s 125?', '["Right to recover damages","Right to recover cost of suit","Right to recover the sums paid as a compromise of the suit","All of the above"]'::jsonb, 3, 'According to Section 125 of The Indian Contract Act, 1872, it defines the Rights of Indemnity Holder when sued, It pertaining to various conditions what kind of losses will be borne by Indemnifier who is been sued by the indemnity holder.'),
(39, 'Which among the following are not to be considered as a contract of indemnity?', '["A contract of Fire Insurance","A contract of Marine Insurance","A contract of Life Insurance","All of the above"]'::jsonb, 2, 'A contract of Life Insurance is not covered un der the contract of indemnity as any act, event or accident which is not In the control of the parties/the act of God is not covered u/s 124.'),
(40, 'A contracts to save B against the consequences of any proceedings, which C may take against B in respect of a certain sum of 500 rupees. This is a:', '["Contract of","Quasi contract","Contract of indemnity","Void guarantee contract"]'::jsonb, 1, NULL),
(41, 'Ravi becomes guarantor for Ashok for the amount which may be given to him by Navin within 6 months. The maximum limit of the said amount is Rs. 1 Lakh. After two months Ravi withdraws his guarantee. Up to the time of revocation of guarantee. Navin had given to Ashok Rs. 20,000. Whether Ravi is discharged from his liabilities to Navin for any subsequent loan? And, whether Ravi is liable if Ashok fails to pay the amount of Rs. 20,000 to Navin?', '["Ravi is discharged from all the liabilities","Ravi is liable to pay the said maximum limit of Rs. 1, 00,000","Ravi is liable to pay the part of the amount of the maximum limit.","Ravi is not discharged for the loan of Rs. 20,000 already given by Navin to Ashok and discharged from all the liabilities after the date of revocation of continuing guarantee"]'::jsonb, 3, 'As per Section 130, continuing guarantee may be revoked, at any time, by the surety by giving a notice to the creditor. However, revocation shall be effective only In respect of future transaction (i.e. the liability of the surety with regard to previous transactions remains unaffected).'),
(42, 'C, the holder of an overdue bill of exchange drawn by A as surety for B, and accepted by B, contracts with X to give time to B. Is A discharged from his liability?', '["A is not discharged from his liability","A is discharged from his liability","A Is discharged from his liability to X","A Is discharged from his liability only to C"]'::jsonb, 0, 'A is not discharged from his liability, since, where a contract to give time to the principal debtor is made by the creditor with a third person and not with the principal debtor, the surety is not discharged.'),
(43, 'Where ''X'' obtains housing loan from LIC Housing and if ''Y'' promises to pay LIC Housing in the event of ''X'' failing to repay - Depict who is the Surety, the Principal Debtor and the Creditor in the given case?', '["X: Principal Debtor; LIC: Surety; Y: Creditor","X: Surety; LIC: Principal Debtor; Y: Creditor","X: Principal Debtor; LIC: Creditor. Y: Surety","X: Surety; LIC: Creditor; Y: Principal Debtor"]'::jsonb, 2, 'Hence In the above case, according to Section 126, Surety is the person who gives the guarantee; Principal Debtor: is the person In respect of whose default the guarantee Is given; Creditor: Is the person to whom the guarantee is given.'),
(44, 'In a Contract of Guarantee there is/are:', '["One contract","Two contracts","Three contracts","Four contracts"]'::jsonb, 2, NULL),
(45, 'A guarantee obtained by a creditor by keeping silence as to material circumstances is:', '["Valid","Voidable","Unenforceable","Invalid"]'::jsonb, 1, NULL),
(46, 'What is the meaning of "Indemnity"?', '["To make good the loss incurred by another person.","To compensate the party who has suffered some loss","To save a party from incurring a loss","All of the above"]'::jsonb, 3, 'According to Section 124 of the Indian Contract Act, 1872. A contract is called a "Contract of Indemnity" If one party promises to save the other from loss caused to him by the conduct of the promisor himself, or by the conduct of any other person.'),
(47, 'When the commencement of surety''s liability arises?', '["When the creditor has sued the principal debtor","On the default by the principal debtor","When the Creditor gives notice to the principal debtor for his default","When the principal debtor gives notice to the surety for such default"]'::jsonb, 1, 'As per Section 128, the liability of surety arises immediately on default by th e principal debtor.'),
(48, 'A gives to C a continuing guarantee to the extent of Rs. 5,000 for the vegetables to be supplied by C to B from time to time on credit. Afterwards, B became embarrassed and without the knowledge of A, B & C contract that C shall continue to supply B with vegetables for ready money, and that the payment shall be applied to both the then existing debt between B & C. Examining the provision of the Indian Contract Act, 1872, decide whether A is liable on his guarantee given to C?', '["Yes, A is liable","No, A is not liable, that take place variation between B & C","No, A is not liable for any of the payment made as surety to C","None of the above"]'::jsonb, 1, 'A is not liable to C for the transaction that take place after variation between B & C, since a surety Is discharged If any transaction is made In a contract of guarantee without the consent of the surety.'),
(49, 'A asks H to kill Z and promises to indemnify H against the consequences. H kills Z and is fined Rs.1000. Can H (indemnity holder) is able to claim the amount of Rs. 1000 from A (indemnifier)?', '["Yes","No","Partly Yes & Partly No.","Can’t say"]'::jsonb, 1, 'No, since the object of the agreement was unlawful as all the essentials of a valid contract must also be present in the contract of indemnity.'),
(50, 'What is the meaning of Contract of Guarantee u/s 126?', '["It is a contract to discharge petty liabilities of a third person in case of his default","It Is a contract to perform the promise of discharging the liabilities to any damages of o third person In case of his default","It is a contract to perform the promise or discharge the liability of a third person in case of his default","None of the above."]'::jsonb, 2, 'According to Section 126 of The Indian Contract Act, 1872, it defines the meaning of "Contract of Guarantee'', where a person himself performs the promise given or accepts to discharge the liability of a third person in case of his default.')
) as v(question_no, question, options, correct_index, hint)
where b.title = 'CA Inter Law MCQs by Darshan Khare'
on conflict (book_id, chapter_no, question_no) do nothing;
`;
