export const SEED_CH12 = `-- Chapter 12: Negotiable Instruments Act, 1881
insert into public.mcq_questions (book_id, chapter_no, chapter_title, question_no, question, options, correct_index, hint)
select b.id, 12, 'Negotiable Instruments Act, 1881', v.question_no, v.question, v.options, v.correct_index, v.hint
from public.books b
cross join lateral (values
(1, 'A person signed a blank acceptance and kept it in his drawer and some person stole it and filled it up for Rs. 29,000 and negotiated it to an innocent person for value, In this case whether signer of the blank acceptance liable to the holder in due course?', '["it was held that the signer to the blank acceptance was liable to the holder in due course","It was held that the signer to the blank acceptance was liable to the holder in due course based on situations","it was held that the signer to the blank acceptance was not liable to the holder in due course","it was held that the signer to the blank acceptance was not liable to the holder in due course based on situations"]'::jsonb, 2, 'Example, a person signed a blank acceptance and kept It in his drawer and some person stole it and fined it up for Rs. 29,000 and negotiated it to an innocent person for value, it was held that the signer to the blank acceptance was not liable to the holde r in due course because he never delivered the instrument intending it to be used as a negotiable instrument. Further, as a condition of liability, the signer as a maker, drawer, endorser or acceptor must deliver the instrument to another. In the absence o f delivery, the signer Is not liable. Furthermore, the paper so signed and delivered must be stamped in accordance with the law prevalent at the time of signing and on delivering otherwise the signer is not estopped from showing that the instrument was fil led without his authority.'),
(2, 'Suraj draws a cheque In favour of Shekhar, a minor. Shekhar endorses the same in favour of Anural. The cheque Is dishonored by the bank on grounds of inadequate funds. Who is the person liable to pay here and Can Anural Sue Shekhar?', '["Person liable to Pay- Suraj, Anural Cannot sue Shekhar","Person liable to Pay- Shekhar, Anural Can sue Shekhar","Person liable to Pay- SuraJ, Anural Can sue Shekhar","No one is liable here"]'::jsonb, 0, 'Capacity to make, draw, accepts etc. of Instruments (Section 26): A minor may draw, endorse, deliver and negotiate such Instruments so as to bind all parties except himself. Nothing herein contained shall be deemed to empower a corporation to make, endorse or accept such instruments except in cases in which, under the law for the time being in force, they are so empowered. Example: Suraj draws a cheque in favour of Shekhar, a minor. Shekhar endorses the same in favour of Anural. The cheque is dishonored by the bank on grounds of Inadequate funds. Here in this case, Shekhar being a minor may draw, endorse, deliver and negotiate the instrument so as to bind all parties except himself. Therefore, Shekhar is not liable. Anural can, thus, proceed against Suraj.'),
(3, 'The main objective of the Negotiable instrument Act, 1881 is to……………….by which Instruments contemplated by it could pass from hand to hand by negotiation like any other goods.', '["Legalize the system","Penalize the person who fails to follow the system","To advise about process of transfer of negotiable instrument","to provide rules and regulation about validity of the instruments"]'::jsonb, 0, 'The source of Indian law relating to such instruments is admittedly the English Common Law. The main objective of the Act is to legalize the system by which instruments contemplat ed by It could pass from hand to hand by negotiation like any othe r goods.'),
(4, 'The Negotiable Instruments Act, 1881 applies to whole of India but excludes………………….', '["Any State Government Transaction","Any local authority Transaction","Any Central Govt. Transactions","Transaction as per Reserve Bank of India Act, 1934, section 21 which provides the Bank to have the right to transact Government business In India"]'::jsonb, 3, 'The Act applies to the whole of India, but nothing herein contained affects the Reserve Bank of India Act, 1934, Section 21 which provides the Bank to have the right to transact Government business In India, or affects any local usage re lating to any instrument in an oriental language.'),
(5, 'The property in a negotiable instrument passes to a………………..transferee for value.', '["Mala fide","Bona fide","Both a and b","Can be Mala fide as well as bona fide"]'::jsonb, 1, 'Negotiable Instruments is an instrument which is transferable (by customs of trade) by delivery, like cash, and is also capable of being sued upon by the person holding it for the time being. The property in such an instrument passes to a bona fide transferee for value.'),
(6, 'A promissory note must contain…….', '["Undertaking","Conditional undertaking","Unconditional undertaking","can be Conditional undertaking or Unconditional undertaking"]'::jsonb, 2, 'According to section 4 of the Negotiable Instruments Act, 1881 "A "promissory note" is an instrument In writing (not being a bank - note or a currency - note) containing an unconditional undertaking signed by the maker, to pay a certain sum of money only to, o r to the order of, a certain person, or to the bearer of the'),
(7, 'Where no rate of interest is specified in the bills of exchange or promissory notes then what is the interest rate used for calculating the interest amount?', '["15% P.A.","18% P.A.","12% P.A.","16% P.A."]'::jsonb, 1, 'When no rate of interest Is specified In the Instrument — interest on the amount due thereon shall be calculated at the rate of 18% per annum, from the date at which the same ought to have been paid by the party charged, until tender or realization of the amount due thereon, or until such date after the institution of a suit to recover such amount as the court directs.'),
(8, 'Who is the person so entitled at the time of such loss or destruction to receive or recover the amount due thereon from the parties where the note, bill or cheque is lost or destroyed?', '["acceptor","Drawer","Payer","holder"]'::jsonb, 3, '"Holder [Section 8] — The "holder of a promissory note, bill of exchange or cheque means — any person - entitled in his own name to the possession thereof, and - to receive or recover the amount due thereon from the parties thereto. Where the note, bill or ch eque is lost or destroyed, its holder is the person so entitled at the time of a. 2 b. 3 c. 9 d. 7'),
(9, 'If the holder of a bill of exchange allows the drawer more than…………………..hours, exclusive of public holidays to consider whether he will accept the same, all previous parties not consenting to such allowance are thereby discharged from liability to such holder', '["36","24","72","48"]'::jsonb, 3, 'Discharge by allowing drawer more than forty - eight hours to accept [Section 83]: - If the holder of a bill of exchange allows the drawer more than forty eight hours, exclusive of public holidays, to consider whether he will accept the same, all previous parties not consenting to such allowance are thereby discharged from liability to such holder.'),
(10, 'In the case of any conviction in a summary trial, it shall be lawful for the Magistrate to pass a sentence of imprisonment for a term how many year?', '["not exceeding three year","not exceeding two year","not exceeding one year","not exceeding four year"]'::jsonb, 2, 'Power of Court to try cases summarily [Sect ion 143]: - In case of summary trial : Provided that in the case of any conviction in a summary trial under this section, it shall be lawful for the Magistrate to pass a sentence of imprisonment for a term not exceeding one year and an amount of fine exceed ing five thousand rupees.'),
(11, 'A promissory note, bill of exchange or cheque…………….', '["may contain words prohibiting transfer or indicating an intention that it shall be transferable","does not contain words prohibiting transfer or Indicating an Intention that It shall not be transferable","does contain words prohibiting transfer or indicating an intention that it shall not be transferable","does not contain words prohibiting transfer or indicating an Intention that It shall be transferable"]'::jsonb, 1, 'A promissory note, bill of exchange or cheque is payable order which is expressed to be so payable or which is expressed to be payable to a particular person, and does not contain words prohibiting transfer or indicating an intention that it shall not be transferable.'),
(12, 'Cheque Is also a bill of exchange but is drawn on a banker and………….', '["payable on demand","Payable after a certain period","at a designated future date or on demand","All of the above"]'::jsonb, 0, 'A combined reading of Section 5 and 6 tells us that a bill of exchange is a negotiable instrument in writing containing an Instruction to a third party to pay a stated sum of money at a designated future date or on demand. Whereas, a cheque is also a bill of exchange but is drawn on a banker and payable on demand.'),
(13, 'Out of the below situation, Where it is called as Instruments payable on demand?', '["promissory note or bill of exchange, in which no time for payment Is specified","A promissory note or bill of exchange, in which Fixed time for payment is specified","A promissory note or bill of exchange, In which specified time for payment is specified to specified person","A promissory note or bill of exchange, in which no time for payment Is specified or fixed time Is specified"]'::jsonb, 0, 'Instruments payable on demand (Section 19) A promissory note or bill of exchange, in which no time for payment is specified, and a cheque, are payable on demand.'),
(14, 'Suraj draws a cheque for Rs.19, 000 and hands it over to Shekhar by way of gift on his marriage, Who is the holder in due course in this case?', '["Suraj","Shekhar","Both a and b","None of the above"]'::jsonb, 3, 'SuraJ draws a cheque for Rs.19, 000 and hands It over to Shekhar by way of gift on his marriage. Shekhar is a holder but not a holder in due course as he does not get the cheque for value and consideration. Hi s title is good and bonafide. As a holder he is entitled to receive Rs.19, 000 from the bank on whom the cheque is drawn'),
(15, 'When the day on which a promissory note or bill of exchange Is at maturity is a public holiday, the instrument shall be deemed to be due on the……………………..', '["next preceding business day","Previous business day","On the same date","Any of the above mentioned date"]'::jsonb, 0, 'When day of maturity is a holiday [Section 25] When the day on which a promissory note or bill of exchange is at maturity is a public holiday, the instrument shall be deemed to be due on the next preceding business day. Explanation: The expression "Public Holiday'' Includes Sundays and any other day declared by the Central Government, by notification in the Official Gazette, to b e a public holiday.'),
(16, 'Where a bill of exchange has been lost before it is overdue, the person who was the holder of it may apply to whom to give him another bill of the same tenor?', '["Drawer","acceptor","Endorser","Payer"]'::jsonb, 0, 'Holder''s right to duplicate of lost bill (Section 454) Where a bill of exchange has been lost before it is overdue, - the person who was the holder of it may apply - to the drawer to give him another bill of the same tenor, - giving security to the drawer, if required.'),
(17, 'Suraj executed a promissory note in favour of Shekhar for Rs. 50 lakhs. The said amount was payable three days after sight. Bhushan, on maturity, presented the promissory note on 1st March, 2017 to Bharat. Bharat made the payments on 4th January, 2017. What is the maturity date of the promissory note and whether Shekhar can recover interest for delay payment?', '["Maturity Date 3rd March 2017, Yes Can recover Interest","Maturity Date 3rd March 2017, No Cannot recover Interest","Maturity Date 4th March 2017, Yes Can recover Interest","Maturity Date 4th March 2017, No Cannot recover Interest"]'::jsonb, 2, 'In calculating the date at which a promissory note or bill of exchange made payable at certain number of days after date or after sight or after a certain event is at maturity, the day of the date, or of presentment for acceptance or sight, or of protest f or non - acceptance, or on which the event happens, shall be excluded. Section 24 of the Negotiable Instruments Act 1881 states that where a bill or note is payable after date or after sight or after happening of a specified event, the time of payment is'),
(18, 'When the maker or holder of a negotiable Instrument signs the same (otherwise than as such maker) for the purpose of negotiation is called as whom?', '["Acceptor","Drawer","Endorser","holder"]'::jsonb, 2, 'Endorsement [Section 15]: When the maker or holder of a negotiable instrument signs the same (otherwise than as such maker) — for the purpose of negotiation - on the back or face thereof or on a slip of paper annexed thereto, or so signs for the same purpose a'),
(19, 'A bill of exchange is a negotiable instalment in writing containing an instruction to a third party to pay a stated sum of money……………………..', '["Payable after a certain period","payable on demand at any point of time","at a designated future date or on demand","All of the above"]'::jsonb, 2, 'A combined reading of section 5 and 6 tells us that a bill of exchange is a negotiable instrument in writing containing an instruction to a third party to pay a stated sum of money at a designated'),
(20, 'As per section 6 of the Negotiable Instruments Act, 1881 Cheque in the electronic form means a cheque drawn in electronic form by using any computer resource, and signed in a secure system with a digital signature……………..', '["without biometric signature","with or without biometric signature","with biometric signature","None of the above"]'::jsonb, 1, 'Cheque [Section 6]: - A cheq ue is a bill of exchange drawn on a specified banker and not expressed to be payable otherwise than on demand and it includes the electronic image of a truncated cheque and a cheque in the electronic form.'),
(21, 'After the drawee of a bill has signed his assent upon the bill, or, if there are more parts thereof than one, upon one of such pans, and delivered the same, or given notice of such signing to the holder or to some person on his behalf, he is called the………………', '["Payer in case of need","acceptor","drawer in case of need","drawee In case of need"]'::jsonb, 1, 'After the drawee of a bill has signed his assent upon the bill, or, If there are more parts thereof than one, upon one of such parts, and delivered the same, or gi ven notice of such signing to the holder or to some person on his behalf, he is called the "acceptor”.'),
(22, 'The maker of a bill of exchange or cheque is called the………. person thereby directed to pay is called the…………..', '["Payer and receiver","Drawee and drawer","Payee and receiver","Drawer and drawee"]'::jsonb, 3, 'The maker of a bill of exchange or cheque is called the "drawer”. The person thereby directed to pay is called the "drawee".'),
(23, 'Validity period for the presentation of cheque in bank is……….', '["3 Months","6 Months","1 Year","2 Years"]'::jsonb, 0, NULL),
(24, 'Any person who for consideration became the possessor of a promissory note, bill of exchange or cheque is called as…………….', '["Acceptor in due course","Drawer","Holder in due course","Payer"]'::jsonb, 2, '"Holder in due course"[Section 9] means any person - who for consideration - became the possessor of a promissory note, bill of exchange or cheque (if payable to bearer), or the payee or endorsee thereof, (If payable to order), - before the amount m entioned in it became payable, and - without having sufficient cause to believe that any defect existed In the title of the person from whom he derived his title.'),
(25, 'Maker of a bill of exchange is called as—', '["Drawer","Drawee","Acceptor","Payee"]'::jsonb, 0, NULL),
(26, 'A promissory note is an instrument in…………….', '["Writing","Photocopy","Xerox","All of the above"]'::jsonb, 0, 'According to section 4 of the Negotiable Instruments Act, 1881 A "promissory note" is an instrument in writing (not being a bank - note or a currency - note) containing an unconditional undertaking signed by the maker, to pay a certain sum of money only to, or to the order of, a certain person, or to the bearer of the instrument.'),
(27, 'A promissory note Is an Instrument in writing containing an unconditional undertaking signed by the whom?', '["Anyone","Payer","Receiver","maker"]'::jsonb, 3, 'According to section 4 of THE NEGOTIABLE INSTRUMENTS ACT, 1881 "A "promissory note" is an instrument In writing (not being a bank - note or a currency - note) containing an unconditional undertaking signed by the maker, to pay a certain sum of money only to, or to the order of, a certain person, or to the bearer of the instrument."'),
(28, 'Offences committed under the Negotiable Instruments Act can be……..', '["Compoundable","Non compoundable","Non compoundable and non-bailable","Bailable"]'::jsonb, 0, NULL),
(29, 'When in the bill the name of any person is given in addition to the drawee to be resorted to In case of need such person is called………………….', '["Payer in case of need","Payee in case of need","drawer In case of need","drawee In case of need"]'::jsonb, 3, 'When in the bill or in any endorsement thereon the name of any person Is given in addition to the drawee to be resorted to in case of need such person Is called a " drawee In case of need"'),
(30, 'As per Section 13 of the Negotiable Instruments Act, 1881 A "negotiable Instrument'' means a promissory note, bill of exchange or cheque payable to whom?', '["order or to payer","order or to receiver","order or to bearer","order or to withdrawer"]'::jsonb, 1, 'Section 13 says, A "negotiable instrument" means a promissory note, bill of exchange or cheque payable either to order or to bearer.')
) as v(question_no, question, options, correct_index, hint)
where b.title = 'CA Inter Law MCQs by Darshan Khare'
on conflict (book_id, chapter_no, question_no) do nothing;
`;
