export const SEED_CH9 = `-- Chapter 9: Declaration of Dividend
insert into public.mcq_questions (book_id, chapter_no, chapter_title, question_no, question, options, correct_index, hint)
select b.id, 9, 'Declaration of Dividend', v.question_no, v.question, v.options, v.correct_index, v.hint
from public.books b
cross join lateral (values
(1, 'Where a dividend is declared by a company and remains unpaid for …………….days, the company shall transfer the amount to unpaid dividend account within another ………….days.', '["30, 30","60, 30","30, 7","60, 7"]'::jsonb, 2, 'Where a dividend has been declared by a company but has not been paid or claimed within 30 days from the date of the declaration to any shareholder entitled to the payment of the dividend, the company shall, within 7 days from the date of expiry of the said period of 30 days, transfer the total amount of dividend which remains unpaid or unclaimed to a special account to be opened by the company in that behalf in any scheduled bank to be called the unpaid dividend account.'),
(2, 'The balance of reserve after withdrawal for dividend shall not fall below…………% of its paid up share capital as appearing in the latest audited financial statement.', '["5","10","15","20"]'::jsonb, 2, NULL),
(3, 'When the dividend is declared at the annual general meeting of the company, it is known as…………', '["Final dividend","Interim dividend","Dividend to equity shareholders","dividend to preference shareholders"]'::jsonb, 0, NULL),
(4, 'Dividend can be declared out of', '["Securities premium reserve","Capital reserve","General reserve","All of the above"]'::jsonb, 2, 'Dividend shall be declared or paid by a company only from its free reserve. No other reserve can be utilized for the purpose of declaration of such dividend.'),
(5, 'For declaration of dividend out of accumulated profits, the total amount to be drawn from such accumulated profits shall not exceed………………… of the sum of its paid up share capital and free reserves as appearing in the latest audited financial statement.', '["2%","5%","10%","20%"]'::jsonb, 2, NULL),
(6, 'Investor Education and Protection Fund(IEPF) shall be utilized for', '["refund of unclaimed and unpaid amounts","promotion of investors awareness","Protection of the interests of investors","All of the above"]'::jsonb, 3, 'Section 125 of the companies Act, 2013, deals with the Investor Education and Protection Fund (IEPF). This fund shall be utilized for refund of unclaimed and unpaid amounts, promotion of investor’s awareness and protection of the interests of investor’s etc. In accordance with provisions of section 125 of the Companies Act, 2013'),
(7, 'Dividend is payable to………….', '["Registered shareholder","Order of registered shareholders","Banker of shareholder","Any of the above"]'::jsonb, 3, 'Dividend shall be payable only to the registered shareholder of the share or to his order or to his banker.'),
(8, 'Dividend shall be declared or paid by a company for any financial year only…………..', '["Out of the profits of the company for that year","Out of the profits of the company for any previous financial year or years","Out of money provided by the Central Government or a state Government for the payment of dividend by the company","All of the above"]'::jsonb, 3, 'Dividend shall be declared or paid by a company for any financial year only – (a) Out of the profits of the company for that year arrived at after providing for depreciation in accordance with the provision of section 123(2), or (b) Out of the profits of the company for any previous financial year or years arrived at after providing for depreciation in accordance with the provisions of that sub section and remaining undistributed, or (c) out of both (a) and (b); or (d) out of money provided by the Central Government or a state Government for the payment of dividend by the company in pursuance of a guarantee given by that Government.'),
(9, 'For declaration of Dividend out of accumulated profits, the rate of dividend declared shall not exceed the average of the rates at which dividend was declared by it in the…….years immediately preceding that year.', '["2","3","5","7"]'::jsonb, 1, 'The rate of dividend declared shall not exceed the average of the rates at which dividend was declared by it in the 3 years immediately preceding that year: Rate of Dividend <(RD1+RD2+RD3)/3Where, RD1, RD2, RD3 are rates at which dividend was declared by it in the 3 years immediately preceding that year. However this rule will not apply if a company has not declared any dividend in each of the 3 preceding financial years.'),
(10, 'When the Board of directors declare dividend between two annual general meetings of the company, such dividend is known as………..', '["Final dividend","Interim dividend","dividend to equity shareholders","dividend Preference shareholders"]'::jsonb, 1, NULL),
(11, 'Dividend on these shares is payable even out of future profit if current year’s profits are insufficient for the purpose.', '["Equity shares","Bonus Equity shares","cumulative preference shares","Non-cumulative preference shares"]'::jsonb, 2, 'A cumulative preference share is one that carries the right to a fixed amount of dividend or dividend at a fixed rate. Such a dividend is payable even out of future profit if current year’s profits are insufficient for the purpose. This means that dividend on these shares accumulates unless it is paid in full and, therefore, the shares are called cumulative preference share'),
(12, 'A ………. Is a payment made by a company to its shareholders, usually as a distribution of profits.', '["Bonus","Dividend","Right shares","ESOP"]'::jsonb, 1, NULL),
(13, 'Any money transferred to the Unpaid dividend Account of a company in pursuance of this section which remains unpaid or unclaimed for a period of………years from the date of such transfer shall be transferred by the company along with interest accrued to INV', '["5","7","8","10"]'::jsonb, 1, 'Any money transferred to the Unpaid dividend Account of a company in pursuance of this section which remains unpaid or unclaimed for a period of 7 years from the date of such transfer shall be transferred by the company along with'),
(14, 'The amount of the dividend, including interim dividend, shall be deposited in a scheduled bank in a separate account within….days from the date of declaration of such dividend.', '["3","5","7","10"]'::jsonb, 1, NULL),
(18, 'Dividends can be paid in the form of ………….', '["Cash","Bonus shares","Right shares","all of the above"]'::jsonb, 0, 'Dividends are payable in cash. Dividends that are payable to the shareholder in cash may be paid by cheque or warrant or in any electronic mode.')
) as v(question_no, question, options, correct_index, hint)
where b.title = 'CA Inter Law MCQs by Darshan Khare'
on conflict (book_id, chapter_no, question_no) do nothing;
`;
