/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTeacherRouteImport } from './routes/_authenticated/teacher'
import { Route as AuthenticatedSyllabusRouteImport } from './routes/_authenticated/syllabus'
import { Route as AuthenticatedStreaksRouteImport } from './routes/_authenticated/streaks'
import { Route as AuthenticatedPastQuestionsRouteImport } from './routes/_authenticated/past-questions'
import { Route as AuthenticatedMockTestRouteImport } from './routes/_authenticated/mock-test'
import { Route as AuthenticatedFormulaSheetsRouteImport } from './routes/_authenticated/formula-sheets'
import { Route as AuthenticatedDoubtsRouteImport } from './routes/_authenticated/doubts'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBookmarksRouteImport } from './routes/_authenticated/bookmarks'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeacherRoute = AuthenticatedTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSyllabusRoute = AuthenticatedSyllabusRouteImport.update({
  id: '/syllabus',
  path: '/syllabus',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStreaksRoute = AuthenticatedStreaksRouteImport.update({
  id: '/streaks',
  path: '/streaks',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPastQuestionsRoute =
  AuthenticatedPastQuestionsRouteImport.update({
    id: '/past-questions',
    path: '/past-questions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMockTestRoute = AuthenticatedMockTestRouteImport.update({
  id: '/mock-test',
  path: '/mock-test',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFormulaSheetsRoute =
  AuthenticatedFormulaSheetsRouteImport.update({
    id: '/formula-sheets',
    path: '/formula-sheets',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDoubtsRoute = AuthenticatedDoubtsRouteImport.update({
  id: '/doubts',
  path: '/doubts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBookmarksRoute = AuthenticatedBookmarksRouteImport.update({
  id: '/bookmarks',
  path: '/bookmarks',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/bookmarks': typeof AuthenticatedBookmarksRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/doubts': typeof AuthenticatedDoubtsRoute
  '/formula-sheets': typeof AuthenticatedFormulaSheetsRoute
  '/mock-test': typeof AuthenticatedMockTestRoute
  '/past-questions': typeof AuthenticatedPastQuestionsRoute
  '/streaks': typeof AuthenticatedStreaksRoute
  '/syllabus': typeof AuthenticatedSyllabusRoute
  '/teacher': typeof AuthenticatedTeacherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/bookmarks': typeof AuthenticatedBookmarksRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/doubts': typeof AuthenticatedDoubtsRoute
  '/formula-sheets': typeof AuthenticatedFormulaSheetsRoute
  '/mock-test': typeof AuthenticatedMockTestRoute
  '/past-questions': typeof AuthenticatedPastQuestionsRoute
  '/streaks': typeof AuthenticatedStreaksRoute
  '/syllabus': typeof AuthenticatedSyllabusRoute
  '/teacher': typeof AuthenticatedTeacherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/bookmarks': typeof AuthenticatedBookmarksRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/doubts': typeof AuthenticatedDoubtsRoute
  '/_authenticated/formula-sheets': typeof AuthenticatedFormulaSheetsRoute
  '/_authenticated/mock-test': typeof AuthenticatedMockTestRoute
  '/_authenticated/past-questions': typeof AuthenticatedPastQuestionsRoute
  '/_authenticated/streaks': typeof AuthenticatedStreaksRoute
  '/_authenticated/syllabus': typeof AuthenticatedSyllabusRoute
  '/_authenticated/teacher': typeof AuthenticatedTeacherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/bookmarks'
    | '/dashboard'
    | '/doubts'
    | '/formula-sheets'
    | '/mock-test'
    | '/past-questions'
    | '/streaks'
    | '/syllabus'
    | '/teacher'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/bookmarks'
    | '/dashboard'
    | '/doubts'
    | '/formula-sheets'
    | '/mock-test'
    | '/past-questions'
    | '/streaks'
    | '/syllabus'
    | '/teacher'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/bookmarks'
    | '/_authenticated/dashboard'
    | '/_authenticated/doubts'
    | '/_authenticated/formula-sheets'
    | '/_authenticated/mock-test'
    | '/_authenticated/past-questions'
    | '/_authenticated/streaks'
    | '/_authenticated/syllabus'
    | '/_authenticated/teacher'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teacher': {
      id: '/_authenticated/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof AuthenticatedTeacherRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/syllabus': {
      id: '/_authenticated/syllabus'
      path: '/syllabus'
      fullPath: '/syllabus'
      preLoaderRoute: typeof AuthenticatedSyllabusRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/streaks': {
      id: '/_authenticated/streaks'
      path: '/streaks'
      fullPath: '/streaks'
      preLoaderRoute: typeof AuthenticatedStreaksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/past-questions': {
      id: '/_authenticated/past-questions'
      path: '/past-questions'
      fullPath: '/past-questions'
      preLoaderRoute: typeof AuthenticatedPastQuestionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mock-test': {
      id: '/_authenticated/mock-test'
      path: '/mock-test'
      fullPath: '/mock-test'
      preLoaderRoute: typeof AuthenticatedMockTestRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/formula-sheets': {
      id: '/_authenticated/formula-sheets'
      path: '/formula-sheets'
      fullPath: '/formula-sheets'
      preLoaderRoute: typeof AuthenticatedFormulaSheetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/doubts': {
      id: '/_authenticated/doubts'
      path: '/doubts'
      fullPath: '/doubts'
      preLoaderRoute: typeof AuthenticatedDoubtsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/bookmarks': {
      id: '/_authenticated/bookmarks'
      path: '/bookmarks'
      fullPath: '/bookmarks'
      preLoaderRoute: typeof AuthenticatedBookmarksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedBookmarksRoute: typeof AuthenticatedBookmarksRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDoubtsRoute: typeof AuthenticatedDoubtsRoute
  AuthenticatedFormulaSheetsRoute: typeof AuthenticatedFormulaSheetsRoute
  AuthenticatedMockTestRoute: typeof AuthenticatedMockTestRoute
  AuthenticatedPastQuestionsRoute: typeof AuthenticatedPastQuestionsRoute
  AuthenticatedStreaksRoute: typeof AuthenticatedStreaksRoute
  AuthenticatedSyllabusRoute: typeof AuthenticatedSyllabusRoute
  AuthenticatedTeacherRoute: typeof AuthenticatedTeacherRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedBookmarksRoute: AuthenticatedBookmarksRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDoubtsRoute: AuthenticatedDoubtsRoute,
  AuthenticatedFormulaSheetsRoute: AuthenticatedFormulaSheetsRoute,
  AuthenticatedMockTestRoute: AuthenticatedMockTestRoute,
  AuthenticatedPastQuestionsRoute: AuthenticatedPastQuestionsRoute,
  AuthenticatedStreaksRoute: AuthenticatedStreaksRoute,
  AuthenticatedSyllabusRoute: AuthenticatedSyllabusRoute,
  AuthenticatedTeacherRoute: AuthenticatedTeacherRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
